apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-java-run-pod
  labels:
    demo: configmap-java-run-pod
    inline-code-editor-demo: 'true'
data:
  HelloWorld.java: |
    public class HelloWorld {
      public static void main(String[] main) {
        System.out.println("Hello world!");
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-java-run-pod
  labels:
    demo: configmap-java-run-pod
    inline-code-editor-demo: 'true'
spec:
  containers:
    - name: runtime
      image: openjdk
      volumeMounts:
        - name: configmap
          mountPath: /configmap
        - name: workdir
          mountPath: /workdir
      workingDir: /workdir
      command:
        - /bin/bash
        - -e
        - -c
        - "cp /configmap/* /workdir/; javac HelloWorld.java; java HelloWorld"
  volumes:
    - name: configmap
      configMap:
        name: configmap-java-run-pod
    - name: workdir
      emptyDir:
        sizeLimit: 500Mi
  restartPolicy: Never
