apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nodejs-run-pod
  labels:
    demo: configmap-nodejs-run-pod
    inline-code-editor-demo: 'true'
data:
  index.js: |
    console.log('Hello world!');
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-nodejs-run-pod
  labels:
    demo: configmap-nodejs-run-pod
    inline-code-editor-demo: 'true'
spec:
  containers:
    - name: runtime
      image: node
      volumeMounts:
        - name: data
          mountPath: /workdir
      workingDir: /workdir
      command: ["node"]
      args: ["index.js"]
  volumes:
    - name: data
      configMap:
        name: configmap-nodejs-run-pod
  restartPolicy: Never
