apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-typescript-bun-run-pod
  labels:
    demo: configmap-typescript-bun-run-pod
    inline-code-editor-demo: 'true'
data:
  index.ts: |
    const message: string = 'Hello world!';
    console.log(message);
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-typescript-bun-run-pod
  labels:
    demo: configmap-typescript-bun-run-pod
    inline-code-editor-demo: 'true'
spec:
  containers:
    - name: runtime
      image: oven/bun
      volumeMounts:
        - name: data
          mountPath: /workdir
      workingDir: /workdir
      command: ["bun"]
      args: ["index.ts"]
  volumes:
    - name: data
      configMap:
        name: configmap-typescript-bun-run-pod
  restartPolicy: Never
