apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-typescript-deno-run-pod
  labels:
    demo: configmap-typescript-deno-run-pod
    inline-code-editor-demo: 'true'
data:
  index.ts: |
    const message: string = 'Hello world!';
    console.log(message);
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-typescript-deno-run-pod
  labels:
    demo: configmap-typescript-deno-run-pod
    inline-code-editor-demo: 'true'
spec:
  containers:
    - name: runtime
      image: denoland/deno
      volumeMounts:
        - name: data
          mountPath: /workdir
      workingDir: /workdir
      command: ["deno"]
      args: ["run", "index.ts"]
  volumes:
    - name: data
      configMap:
        name: configmap-typescript-deno-run-pod
  restartPolicy: Never
