apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-golang-build-and-run-pod
  labels:
    demo: configmap-golang-build-and-run-pod
    inline-code-editor-demo: 'true'
data:
  go.mod: |
    module example

    go 1.21.4
  main.go: |
    package main

    import "fmt"

    func main() {
      fmt.Println("Hello world!")
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-golang-build-and-run-pod
  labels:
    demo: configmap-golang-build-and-run-pod
    inline-code-editor-demo: 'true'
spec:
  containers:
    - name: runtime
      image: golang
      volumeMounts:
        - name: configmap
          mountPath: /configmap
        - name: workdir
          mountPath: /workdir
      workingDir: /workdir
      command:
        - /bin/bash
        - -e
        - -c
        - "cp /configmap/* /workdir/; go build .; ./example"
  volumes:
    - name: configmap
      configMap:
        name: configmap-golang-build-and-run-pod
    - name: workdir
      emptyDir:
        sizeLimit: 500Mi
  restartPolicy: Never
