apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-python-run-pod
  labels:
    demo: configmap-python-run-pod
    inline-code-editor-demo: 'true'
data:
  script.py: |
    print("Hello world!")
---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-python-run-pod
  labels:
    demo: configmap-python-run-pod
    inline-code-editor-demo: 'true'
spec:
  containers:
    - name: runtime
      image: python
      volumeMounts:
        - name: data
          mountPath: /workdir
      workingDir: /workdir
      command: ["python"]
      args: ["script.py"]
  volumes:
    - name: data
      configMap:
        name: configmap-python-run-pod
  restartPolicy: Never
